/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiInngestRouteImport } from './routes/api/inngest'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedCalendarRouteImport } from './routes/_authed/calendar'
import { Route as AuthPinterestCallbackRouteImport } from './routes/auth.pinterest.callback'
import { Route as AuthedProjectsIdRouteImport } from './routes/_authed/projects/$id'
import { Route as AuthedProjectsProjectIdPinsPinIdRouteImport } from './routes/_authed/projects/$projectId/pins/$pinId'
import { Route as AuthedProjectsProjectIdArticlesArticleIdRouteImport } from './routes/_authed/projects/$projectId/articles/$articleId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInngestRoute = ApiInngestRouteImport.update({
  id: '/api/inngest',
  path: '/api/inngest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCalendarRoute = AuthedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthPinterestCallbackRoute = AuthPinterestCallbackRouteImport.update({
  id: '/auth/pinterest/callback',
  path: '/auth/pinterest/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedProjectsIdRoute = AuthedProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProjectsProjectIdPinsPinIdRoute =
  AuthedProjectsProjectIdPinsPinIdRouteImport.update({
    id: '/projects/$projectId/pins/$pinId',
    path: '/projects/$projectId/pins/$pinId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedProjectsProjectIdArticlesArticleIdRoute =
  AuthedProjectsProjectIdArticlesArticleIdRouteImport.update({
    id: '/projects/$projectId/articles/$articleId',
    path: '/projects/$projectId/articles/$articleId',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/calendar': typeof AuthedCalendarRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/api/inngest': typeof ApiInngestRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/projects/$id': typeof AuthedProjectsIdRoute
  '/auth/pinterest/callback': typeof AuthPinterestCallbackRoute
  '/projects/$projectId/articles/$articleId': typeof AuthedProjectsProjectIdArticlesArticleIdRoute
  '/projects/$projectId/pins/$pinId': typeof AuthedProjectsProjectIdPinsPinIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/calendar': typeof AuthedCalendarRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/api/inngest': typeof ApiInngestRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/projects/$id': typeof AuthedProjectsIdRoute
  '/auth/pinterest/callback': typeof AuthPinterestCallbackRoute
  '/projects/$projectId/articles/$articleId': typeof AuthedProjectsProjectIdArticlesArticleIdRoute
  '/projects/$projectId/pins/$pinId': typeof AuthedProjectsProjectIdPinsPinIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/calendar': typeof AuthedCalendarRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/api/inngest': typeof ApiInngestRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authed/projects/$id': typeof AuthedProjectsIdRoute
  '/auth/pinterest/callback': typeof AuthPinterestCallbackRoute
  '/_authed/projects/$projectId/articles/$articleId': typeof AuthedProjectsProjectIdArticlesArticleIdRoute
  '/_authed/projects/$projectId/pins/$pinId': typeof AuthedProjectsProjectIdPinsPinIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/calendar'
    | '/dashboard'
    | '/api/inngest'
    | '/auth/callback'
    | '/projects/$id'
    | '/auth/pinterest/callback'
    | '/projects/$projectId/articles/$articleId'
    | '/projects/$projectId/pins/$pinId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/calendar'
    | '/dashboard'
    | '/api/inngest'
    | '/auth/callback'
    | '/projects/$id'
    | '/auth/pinterest/callback'
    | '/projects/$projectId/articles/$articleId'
    | '/projects/$projectId/pins/$pinId'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/_authed/calendar'
    | '/_authed/dashboard'
    | '/api/inngest'
    | '/auth/callback'
    | '/_authed/projects/$id'
    | '/auth/pinterest/callback'
    | '/_authed/projects/$projectId/articles/$articleId'
    | '/_authed/projects/$projectId/pins/$pinId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiInngestRoute: typeof ApiInngestRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthPinterestCallbackRoute: typeof AuthPinterestCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inngest': {
      id: '/api/inngest'
      path: '/api/inngest'
      fullPath: '/api/inngest'
      preLoaderRoute: typeof ApiInngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/calendar': {
      id: '/_authed/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthedCalendarRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/auth/pinterest/callback': {
      id: '/auth/pinterest/callback'
      path: '/auth/pinterest/callback'
      fullPath: '/auth/pinterest/callback'
      preLoaderRoute: typeof AuthPinterestCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/projects/$id': {
      id: '/_authed/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AuthedProjectsIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/projects/$projectId/pins/$pinId': {
      id: '/_authed/projects/$projectId/pins/$pinId'
      path: '/projects/$projectId/pins/$pinId'
      fullPath: '/projects/$projectId/pins/$pinId'
      preLoaderRoute: typeof AuthedProjectsProjectIdPinsPinIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/projects/$projectId/articles/$articleId': {
      id: '/_authed/projects/$projectId/articles/$articleId'
      path: '/projects/$projectId/articles/$articleId'
      fullPath: '/projects/$projectId/articles/$articleId'
      preLoaderRoute: typeof AuthedProjectsProjectIdArticlesArticleIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedCalendarRoute: typeof AuthedCalendarRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedProjectsIdRoute: typeof AuthedProjectsIdRoute
  AuthedProjectsProjectIdArticlesArticleIdRoute: typeof AuthedProjectsProjectIdArticlesArticleIdRoute
  AuthedProjectsProjectIdPinsPinIdRoute: typeof AuthedProjectsProjectIdPinsPinIdRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedCalendarRoute: AuthedCalendarRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedProjectsIdRoute: AuthedProjectsIdRoute,
  AuthedProjectsProjectIdArticlesArticleIdRoute:
    AuthedProjectsProjectIdArticlesArticleIdRoute,
  AuthedProjectsProjectIdPinsPinIdRoute: AuthedProjectsProjectIdPinsPinIdRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiInngestRoute: ApiInngestRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthPinterestCallbackRoute: AuthPinterestCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
