/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedProjectsIndexRouteImport } from './routes/_authed/projects/index'
import { Route as AuthPinterestCallbackRouteImport } from './routes/auth.pinterest.callback'
import { Route as AuthedProjectsProjectIdIndexRouteImport } from './routes/_authed/projects/$projectId/index'
import { Route as AuthedProjectsProjectIdCreatePinRouteImport } from './routes/_authed/projects/$projectId/create-pin'
import { Route as AuthedProjectsProjectIdCalendarRouteImport } from './routes/_authed/projects/$projectId/calendar'
import { Route as AuthedProjectsProjectIdPinsIndexRouteImport } from './routes/_authed/projects/$projectId/pins/index'
import { Route as AuthedProjectsProjectIdArticlesIndexRouteImport } from './routes/_authed/projects/$projectId/articles/index'
import { Route as AuthedProjectsProjectIdPinsPinIdRouteImport } from './routes/_authed/projects/$projectId/pins/$pinId'
import { Route as AuthedProjectsProjectIdArticlesArticleIdRouteImport } from './routes/_authed/projects/$projectId/articles/$articleId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProjectsIndexRoute = AuthedProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthPinterestCallbackRoute = AuthPinterestCallbackRouteImport.update({
  id: '/auth/pinterest/callback',
  path: '/auth/pinterest/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedProjectsProjectIdIndexRoute =
  AuthedProjectsProjectIdIndexRouteImport.update({
    id: '/projects/$projectId/',
    path: '/projects/$projectId/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedProjectsProjectIdCreatePinRoute =
  AuthedProjectsProjectIdCreatePinRouteImport.update({
    id: '/projects/$projectId/create-pin',
    path: '/projects/$projectId/create-pin',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedProjectsProjectIdCalendarRoute =
  AuthedProjectsProjectIdCalendarRouteImport.update({
    id: '/projects/$projectId/calendar',
    path: '/projects/$projectId/calendar',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedProjectsProjectIdPinsIndexRoute =
  AuthedProjectsProjectIdPinsIndexRouteImport.update({
    id: '/projects/$projectId/pins/',
    path: '/projects/$projectId/pins/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedProjectsProjectIdArticlesIndexRoute =
  AuthedProjectsProjectIdArticlesIndexRouteImport.update({
    id: '/projects/$projectId/articles/',
    path: '/projects/$projectId/articles/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedProjectsProjectIdPinsPinIdRoute =
  AuthedProjectsProjectIdPinsPinIdRouteImport.update({
    id: '/projects/$projectId/pins/$pinId',
    path: '/projects/$projectId/pins/$pinId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedProjectsProjectIdArticlesArticleIdRoute =
  AuthedProjectsProjectIdArticlesArticleIdRouteImport.update({
    id: '/projects/$projectId/articles/$articleId',
    path: '/projects/$projectId/articles/$articleId',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/pinterest/callback': typeof AuthPinterestCallbackRoute
  '/projects/': typeof AuthedProjectsIndexRoute
  '/projects/$projectId/calendar': typeof AuthedProjectsProjectIdCalendarRoute
  '/projects/$projectId/create-pin': typeof AuthedProjectsProjectIdCreatePinRoute
  '/projects/$projectId/': typeof AuthedProjectsProjectIdIndexRoute
  '/projects/$projectId/articles/$articleId': typeof AuthedProjectsProjectIdArticlesArticleIdRoute
  '/projects/$projectId/pins/$pinId': typeof AuthedProjectsProjectIdPinsPinIdRoute
  '/projects/$projectId/articles/': typeof AuthedProjectsProjectIdArticlesIndexRoute
  '/projects/$projectId/pins/': typeof AuthedProjectsProjectIdPinsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/pinterest/callback': typeof AuthPinterestCallbackRoute
  '/projects': typeof AuthedProjectsIndexRoute
  '/projects/$projectId/calendar': typeof AuthedProjectsProjectIdCalendarRoute
  '/projects/$projectId/create-pin': typeof AuthedProjectsProjectIdCreatePinRoute
  '/projects/$projectId': typeof AuthedProjectsProjectIdIndexRoute
  '/projects/$projectId/articles/$articleId': typeof AuthedProjectsProjectIdArticlesArticleIdRoute
  '/projects/$projectId/pins/$pinId': typeof AuthedProjectsProjectIdPinsPinIdRoute
  '/projects/$projectId/articles': typeof AuthedProjectsProjectIdArticlesIndexRoute
  '/projects/$projectId/pins': typeof AuthedProjectsProjectIdPinsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/pinterest/callback': typeof AuthPinterestCallbackRoute
  '/_authed/projects/': typeof AuthedProjectsIndexRoute
  '/_authed/projects/$projectId/calendar': typeof AuthedProjectsProjectIdCalendarRoute
  '/_authed/projects/$projectId/create-pin': typeof AuthedProjectsProjectIdCreatePinRoute
  '/_authed/projects/$projectId/': typeof AuthedProjectsProjectIdIndexRoute
  '/_authed/projects/$projectId/articles/$articleId': typeof AuthedProjectsProjectIdArticlesArticleIdRoute
  '/_authed/projects/$projectId/pins/$pinId': typeof AuthedProjectsProjectIdPinsPinIdRoute
  '/_authed/projects/$projectId/articles/': typeof AuthedProjectsProjectIdArticlesIndexRoute
  '/_authed/projects/$projectId/pins/': typeof AuthedProjectsProjectIdPinsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/auth/callback'
    | '/auth/pinterest/callback'
    | '/projects/'
    | '/projects/$projectId/calendar'
    | '/projects/$projectId/create-pin'
    | '/projects/$projectId/'
    | '/projects/$projectId/articles/$articleId'
    | '/projects/$projectId/pins/$pinId'
    | '/projects/$projectId/articles/'
    | '/projects/$projectId/pins/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/auth/callback'
    | '/auth/pinterest/callback'
    | '/projects'
    | '/projects/$projectId/calendar'
    | '/projects/$projectId/create-pin'
    | '/projects/$projectId'
    | '/projects/$projectId/articles/$articleId'
    | '/projects/$projectId/pins/$pinId'
    | '/projects/$projectId/articles'
    | '/projects/$projectId/pins'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/_authed/dashboard'
    | '/auth/callback'
    | '/auth/pinterest/callback'
    | '/_authed/projects/'
    | '/_authed/projects/$projectId/calendar'
    | '/_authed/projects/$projectId/create-pin'
    | '/_authed/projects/$projectId/'
    | '/_authed/projects/$projectId/articles/$articleId'
    | '/_authed/projects/$projectId/pins/$pinId'
    | '/_authed/projects/$projectId/articles/'
    | '/_authed/projects/$projectId/pins/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthPinterestCallbackRoute: typeof AuthPinterestCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/projects/': {
      id: '/_authed/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthedProjectsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/auth/pinterest/callback': {
      id: '/auth/pinterest/callback'
      path: '/auth/pinterest/callback'
      fullPath: '/auth/pinterest/callback'
      preLoaderRoute: typeof AuthPinterestCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/projects/$projectId/': {
      id: '/_authed/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof AuthedProjectsProjectIdIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/projects/$projectId/create-pin': {
      id: '/_authed/projects/$projectId/create-pin'
      path: '/projects/$projectId/create-pin'
      fullPath: '/projects/$projectId/create-pin'
      preLoaderRoute: typeof AuthedProjectsProjectIdCreatePinRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/projects/$projectId/calendar': {
      id: '/_authed/projects/$projectId/calendar'
      path: '/projects/$projectId/calendar'
      fullPath: '/projects/$projectId/calendar'
      preLoaderRoute: typeof AuthedProjectsProjectIdCalendarRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/projects/$projectId/pins/': {
      id: '/_authed/projects/$projectId/pins/'
      path: '/projects/$projectId/pins'
      fullPath: '/projects/$projectId/pins/'
      preLoaderRoute: typeof AuthedProjectsProjectIdPinsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/projects/$projectId/articles/': {
      id: '/_authed/projects/$projectId/articles/'
      path: '/projects/$projectId/articles'
      fullPath: '/projects/$projectId/articles/'
      preLoaderRoute: typeof AuthedProjectsProjectIdArticlesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/projects/$projectId/pins/$pinId': {
      id: '/_authed/projects/$projectId/pins/$pinId'
      path: '/projects/$projectId/pins/$pinId'
      fullPath: '/projects/$projectId/pins/$pinId'
      preLoaderRoute: typeof AuthedProjectsProjectIdPinsPinIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/projects/$projectId/articles/$articleId': {
      id: '/_authed/projects/$projectId/articles/$articleId'
      path: '/projects/$projectId/articles/$articleId'
      fullPath: '/projects/$projectId/articles/$articleId'
      preLoaderRoute: typeof AuthedProjectsProjectIdArticlesArticleIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedProjectsIndexRoute: typeof AuthedProjectsIndexRoute
  AuthedProjectsProjectIdCalendarRoute: typeof AuthedProjectsProjectIdCalendarRoute
  AuthedProjectsProjectIdCreatePinRoute: typeof AuthedProjectsProjectIdCreatePinRoute
  AuthedProjectsProjectIdIndexRoute: typeof AuthedProjectsProjectIdIndexRoute
  AuthedProjectsProjectIdArticlesArticleIdRoute: typeof AuthedProjectsProjectIdArticlesArticleIdRoute
  AuthedProjectsProjectIdPinsPinIdRoute: typeof AuthedProjectsProjectIdPinsPinIdRoute
  AuthedProjectsProjectIdArticlesIndexRoute: typeof AuthedProjectsProjectIdArticlesIndexRoute
  AuthedProjectsProjectIdPinsIndexRoute: typeof AuthedProjectsProjectIdPinsIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedProjectsIndexRoute: AuthedProjectsIndexRoute,
  AuthedProjectsProjectIdCalendarRoute: AuthedProjectsProjectIdCalendarRoute,
  AuthedProjectsProjectIdCreatePinRoute: AuthedProjectsProjectIdCreatePinRoute,
  AuthedProjectsProjectIdIndexRoute: AuthedProjectsProjectIdIndexRoute,
  AuthedProjectsProjectIdArticlesArticleIdRoute:
    AuthedProjectsProjectIdArticlesArticleIdRoute,
  AuthedProjectsProjectIdPinsPinIdRoute: AuthedProjectsProjectIdPinsPinIdRoute,
  AuthedProjectsProjectIdArticlesIndexRoute:
    AuthedProjectsProjectIdArticlesIndexRoute,
  AuthedProjectsProjectIdPinsIndexRoute: AuthedProjectsProjectIdPinsIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthPinterestCallbackRoute: AuthPinterestCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
